
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Corsat.DAL;
namespace Corsat.BLL
{
	public class Course_Data : _Course_Data
	{
		public Course_Data()
		{
		
		}
	}
}
