
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using Corsat.DAL;
namespace Corsat.BLL
{
	public class Course_Data_DataType : _Course_Data_DataType
	{
		public Course_Data_DataType()
		{
		
		}
	}
}
