
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Corsat.DAL
{
	public abstract class _News : SqlClientEntity
	{
		public _News()
		{
			this.QuerySource = "News";
			this.MappingName = "News";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_NewsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int NewsID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.NewsID, NewsID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_NewsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter NewsID
			{
				get
				{
					return new SqlParameter("@NewsID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Title
			{
				get
				{
					return new SqlParameter("@Title", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter Brief
			{
				get
				{
					return new SqlParameter("@Brief", SqlDbType.NVarChar, 500);
				}
			}
			
			public static SqlParameter Body
			{
				get
				{
					return new SqlParameter("@Body", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter MainPicturePath
			{
				get
				{
					return new SqlParameter("@MainPicturePath", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter PublishedDate
			{
				get
				{
					return new SqlParameter("@PublishedDate", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string NewsID = "NewsID";
            public const string Title = "Title";
            public const string Brief = "Brief";
            public const string Body = "Body";
            public const string MainPicturePath = "MainPicturePath";
            public const string PublishedDate = "PublishedDate";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[NewsID] = _News.PropertyNames.NewsID;
					ht[Title] = _News.PropertyNames.Title;
					ht[Brief] = _News.PropertyNames.Brief;
					ht[Body] = _News.PropertyNames.Body;
					ht[MainPicturePath] = _News.PropertyNames.MainPicturePath;
					ht[PublishedDate] = _News.PropertyNames.PublishedDate;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string NewsID = "NewsID";
            public const string Title = "Title";
            public const string Brief = "Brief";
            public const string Body = "Body";
            public const string MainPicturePath = "MainPicturePath";
            public const string PublishedDate = "PublishedDate";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[NewsID] = _News.ColumnNames.NewsID;
					ht[Title] = _News.ColumnNames.Title;
					ht[Brief] = _News.ColumnNames.Brief;
					ht[Body] = _News.ColumnNames.Body;
					ht[MainPicturePath] = _News.ColumnNames.MainPicturePath;
					ht[PublishedDate] = _News.ColumnNames.PublishedDate;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string NewsID = "s_NewsID";
            public const string Title = "s_Title";
            public const string Brief = "s_Brief";
            public const string Body = "s_Body";
            public const string MainPicturePath = "s_MainPicturePath";
            public const string PublishedDate = "s_PublishedDate";

		}
		#endregion		
		
		#region Properties
	
		public virtual int NewsID
	    {
			get
	        {
				return base.Getint(ColumnNames.NewsID);
			}
			set
	        {
				base.Setint(ColumnNames.NewsID, value);
			}
		}

		public virtual string Title
	    {
			get
	        {
				return base.Getstring(ColumnNames.Title);
			}
			set
	        {
				base.Setstring(ColumnNames.Title, value);
			}
		}

		public virtual string Brief
	    {
			get
	        {
				return base.Getstring(ColumnNames.Brief);
			}
			set
	        {
				base.Setstring(ColumnNames.Brief, value);
			}
		}

		public virtual string Body
	    {
			get
	        {
				return base.Getstring(ColumnNames.Body);
			}
			set
	        {
				base.Setstring(ColumnNames.Body, value);
			}
		}

		public virtual string MainPicturePath
	    {
			get
	        {
				return base.Getstring(ColumnNames.MainPicturePath);
			}
			set
	        {
				base.Setstring(ColumnNames.MainPicturePath, value);
			}
		}

		public virtual DateTime PublishedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.PublishedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.PublishedDate, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_NewsID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NewsID) ? string.Empty : base.GetintAsString(ColumnNames.NewsID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NewsID);
				else
					this.NewsID = base.SetintAsString(ColumnNames.NewsID, value);
			}
		}

		public virtual string s_Title
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Title) ? string.Empty : base.GetstringAsString(ColumnNames.Title);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Title);
				else
					this.Title = base.SetstringAsString(ColumnNames.Title, value);
			}
		}

		public virtual string s_Brief
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Brief) ? string.Empty : base.GetstringAsString(ColumnNames.Brief);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Brief);
				else
					this.Brief = base.SetstringAsString(ColumnNames.Brief, value);
			}
		}

		public virtual string s_Body
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Body) ? string.Empty : base.GetstringAsString(ColumnNames.Body);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Body);
				else
					this.Body = base.SetstringAsString(ColumnNames.Body, value);
			}
		}

		public virtual string s_MainPicturePath
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MainPicturePath) ? string.Empty : base.GetstringAsString(ColumnNames.MainPicturePath);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MainPicturePath);
				else
					this.MainPicturePath = base.SetstringAsString(ColumnNames.MainPicturePath, value);
			}
		}

		public virtual string s_PublishedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PublishedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.PublishedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PublishedDate);
				else
					this.PublishedDate = base.SetDateTimeAsString(ColumnNames.PublishedDate, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter NewsID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NewsID, Parameters.NewsID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Title
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Brief
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Brief, Parameters.Brief);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Body
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Body, Parameters.Body);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MainPicturePath
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MainPicturePath, Parameters.MainPicturePath);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PublishedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PublishedDate, Parameters.PublishedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter NewsID
		    {
				get
		        {
					if(_NewsID_W == null)
	        	    {
						_NewsID_W = TearOff.NewsID;
					}
					return _NewsID_W;
				}
			}

			public WhereParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public WhereParameter Brief
		    {
				get
		        {
					if(_Brief_W == null)
	        	    {
						_Brief_W = TearOff.Brief;
					}
					return _Brief_W;
				}
			}

			public WhereParameter Body
		    {
				get
		        {
					if(_Body_W == null)
	        	    {
						_Body_W = TearOff.Body;
					}
					return _Body_W;
				}
			}

			public WhereParameter MainPicturePath
		    {
				get
		        {
					if(_MainPicturePath_W == null)
	        	    {
						_MainPicturePath_W = TearOff.MainPicturePath;
					}
					return _MainPicturePath_W;
				}
			}

			public WhereParameter PublishedDate
		    {
				get
		        {
					if(_PublishedDate_W == null)
	        	    {
						_PublishedDate_W = TearOff.PublishedDate;
					}
					return _PublishedDate_W;
				}
			}

			private WhereParameter _NewsID_W = null;
			private WhereParameter _Title_W = null;
			private WhereParameter _Brief_W = null;
			private WhereParameter _Body_W = null;
			private WhereParameter _MainPicturePath_W = null;
			private WhereParameter _PublishedDate_W = null;

			public void WhereClauseReset()
			{
				_NewsID_W = null;
				_Title_W = null;
				_Brief_W = null;
				_Body_W = null;
				_MainPicturePath_W = null;
				_PublishedDate_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter NewsID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NewsID, Parameters.NewsID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Title
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Brief
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Brief, Parameters.Brief);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Body
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Body, Parameters.Body);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MainPicturePath
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MainPicturePath, Parameters.MainPicturePath);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PublishedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PublishedDate, Parameters.PublishedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter NewsID
		    {
				get
		        {
					if(_NewsID_W == null)
	        	    {
						_NewsID_W = TearOff.NewsID;
					}
					return _NewsID_W;
				}
			}

			public AggregateParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public AggregateParameter Brief
		    {
				get
		        {
					if(_Brief_W == null)
	        	    {
						_Brief_W = TearOff.Brief;
					}
					return _Brief_W;
				}
			}

			public AggregateParameter Body
		    {
				get
		        {
					if(_Body_W == null)
	        	    {
						_Body_W = TearOff.Body;
					}
					return _Body_W;
				}
			}

			public AggregateParameter MainPicturePath
		    {
				get
		        {
					if(_MainPicturePath_W == null)
	        	    {
						_MainPicturePath_W = TearOff.MainPicturePath;
					}
					return _MainPicturePath_W;
				}
			}

			public AggregateParameter PublishedDate
		    {
				get
		        {
					if(_PublishedDate_W == null)
	        	    {
						_PublishedDate_W = TearOff.PublishedDate;
					}
					return _PublishedDate_W;
				}
			}

			private AggregateParameter _NewsID_W = null;
			private AggregateParameter _Title_W = null;
			private AggregateParameter _Brief_W = null;
			private AggregateParameter _Body_W = null;
			private AggregateParameter _MainPicturePath_W = null;
			private AggregateParameter _PublishedDate_W = null;

			public void AggregateClauseReset()
			{
				_NewsID_W = null;
				_Title_W = null;
				_Brief_W = null;
				_Body_W = null;
				_MainPicturePath_W = null;
				_PublishedDate_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_NewsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.NewsID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_NewsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_NewsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.NewsID);
			p.SourceColumn = ColumnNames.NewsID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.NewsID);
			p.SourceColumn = ColumnNames.NewsID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Title);
			p.SourceColumn = ColumnNames.Title;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Brief);
			p.SourceColumn = ColumnNames.Brief;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Body);
			p.SourceColumn = ColumnNames.Body;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MainPicturePath);
			p.SourceColumn = ColumnNames.MainPicturePath;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PublishedDate);
			p.SourceColumn = ColumnNames.PublishedDate;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
