
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Corsat.DAL
{
	public abstract class _TimePlan : SqlClientEntity
	{
		public _TimePlan()
		{
			this.QuerySource = "TimePlan";
			this.MappingName = "TimePlan";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TimePlanLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int TimePlanID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.TimePlanID, TimePlanID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_TimePlanLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter TimePlanID
			{
				get
				{
					return new SqlParameter("@TimePlanID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Title
			{
				get
				{
					return new SqlParameter("@Title", SqlDbType.NVarChar, 800);
				}
			}
			
			public static SqlParameter IsVisible
			{
				get
				{
					return new SqlParameter("@IsVisible", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter PublishedDate
			{
				get
				{
					return new SqlParameter("@PublishedDate", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string TimePlanID = "TimePlanID";
            public const string Title = "Title";
            public const string IsVisible = "IsVisible";
            public const string PublishedDate = "PublishedDate";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TimePlanID] = _TimePlan.PropertyNames.TimePlanID;
					ht[Title] = _TimePlan.PropertyNames.Title;
					ht[IsVisible] = _TimePlan.PropertyNames.IsVisible;
					ht[PublishedDate] = _TimePlan.PropertyNames.PublishedDate;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string TimePlanID = "TimePlanID";
            public const string Title = "Title";
            public const string IsVisible = "IsVisible";
            public const string PublishedDate = "PublishedDate";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[TimePlanID] = _TimePlan.ColumnNames.TimePlanID;
					ht[Title] = _TimePlan.ColumnNames.Title;
					ht[IsVisible] = _TimePlan.ColumnNames.IsVisible;
					ht[PublishedDate] = _TimePlan.ColumnNames.PublishedDate;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string TimePlanID = "s_TimePlanID";
            public const string Title = "s_Title";
            public const string IsVisible = "s_IsVisible";
            public const string PublishedDate = "s_PublishedDate";

		}
		#endregion		
		
		#region Properties
	
		public virtual int TimePlanID
	    {
			get
	        {
				return base.Getint(ColumnNames.TimePlanID);
			}
			set
	        {
				base.Setint(ColumnNames.TimePlanID, value);
			}
		}

		public virtual string Title
	    {
			get
	        {
				return base.Getstring(ColumnNames.Title);
			}
			set
	        {
				base.Setstring(ColumnNames.Title, value);
			}
		}

		public virtual bool IsVisible
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsVisible);
			}
			set
	        {
				base.Setbool(ColumnNames.IsVisible, value);
			}
		}

		public virtual DateTime PublishedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.PublishedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.PublishedDate, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_TimePlanID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TimePlanID) ? string.Empty : base.GetintAsString(ColumnNames.TimePlanID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TimePlanID);
				else
					this.TimePlanID = base.SetintAsString(ColumnNames.TimePlanID, value);
			}
		}

		public virtual string s_Title
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Title) ? string.Empty : base.GetstringAsString(ColumnNames.Title);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Title);
				else
					this.Title = base.SetstringAsString(ColumnNames.Title, value);
			}
		}

		public virtual string s_IsVisible
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsVisible) ? string.Empty : base.GetboolAsString(ColumnNames.IsVisible);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsVisible);
				else
					this.IsVisible = base.SetboolAsString(ColumnNames.IsVisible, value);
			}
		}

		public virtual string s_PublishedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PublishedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.PublishedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PublishedDate);
				else
					this.PublishedDate = base.SetDateTimeAsString(ColumnNames.PublishedDate, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter TimePlanID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TimePlanID, Parameters.TimePlanID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Title
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsVisible
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsVisible, Parameters.IsVisible);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PublishedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PublishedDate, Parameters.PublishedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter TimePlanID
		    {
				get
		        {
					if(_TimePlanID_W == null)
	        	    {
						_TimePlanID_W = TearOff.TimePlanID;
					}
					return _TimePlanID_W;
				}
			}

			public WhereParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public WhereParameter IsVisible
		    {
				get
		        {
					if(_IsVisible_W == null)
	        	    {
						_IsVisible_W = TearOff.IsVisible;
					}
					return _IsVisible_W;
				}
			}

			public WhereParameter PublishedDate
		    {
				get
		        {
					if(_PublishedDate_W == null)
	        	    {
						_PublishedDate_W = TearOff.PublishedDate;
					}
					return _PublishedDate_W;
				}
			}

			private WhereParameter _TimePlanID_W = null;
			private WhereParameter _Title_W = null;
			private WhereParameter _IsVisible_W = null;
			private WhereParameter _PublishedDate_W = null;

			public void WhereClauseReset()
			{
				_TimePlanID_W = null;
				_Title_W = null;
				_IsVisible_W = null;
				_PublishedDate_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter TimePlanID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TimePlanID, Parameters.TimePlanID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Title
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsVisible
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsVisible, Parameters.IsVisible);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PublishedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PublishedDate, Parameters.PublishedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter TimePlanID
		    {
				get
		        {
					if(_TimePlanID_W == null)
	        	    {
						_TimePlanID_W = TearOff.TimePlanID;
					}
					return _TimePlanID_W;
				}
			}

			public AggregateParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public AggregateParameter IsVisible
		    {
				get
		        {
					if(_IsVisible_W == null)
	        	    {
						_IsVisible_W = TearOff.IsVisible;
					}
					return _IsVisible_W;
				}
			}

			public AggregateParameter PublishedDate
		    {
				get
		        {
					if(_PublishedDate_W == null)
	        	    {
						_PublishedDate_W = TearOff.PublishedDate;
					}
					return _PublishedDate_W;
				}
			}

			private AggregateParameter _TimePlanID_W = null;
			private AggregateParameter _Title_W = null;
			private AggregateParameter _IsVisible_W = null;
			private AggregateParameter _PublishedDate_W = null;

			public void AggregateClauseReset()
			{
				_TimePlanID_W = null;
				_Title_W = null;
				_IsVisible_W = null;
				_PublishedDate_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TimePlanInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.TimePlanID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TimePlanUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_TimePlanDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.TimePlanID);
			p.SourceColumn = ColumnNames.TimePlanID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.TimePlanID);
			p.SourceColumn = ColumnNames.TimePlanID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Title);
			p.SourceColumn = ColumnNames.Title;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsVisible);
			p.SourceColumn = ColumnNames.IsVisible;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PublishedDate);
			p.SourceColumn = ColumnNames.PublishedDate;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
