
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Corsat.DAL
{
	public abstract class _UserCourse : SqlClientEntity
	{
		public _UserCourse()
		{
			this.QuerySource = "UserCourse";
			this.MappingName = "UserCourse";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserCourseLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int CourseID, DateTime CourseDate, Guid UserID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.CourseID, CourseID);

parameters.Add(Parameters.CourseDate, CourseDate);

parameters.Add(Parameters.UserID, UserID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_UserCourseLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter CourseID
			{
				get
				{
					return new SqlParameter("@CourseID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Grade
			{
				get
				{
					return new SqlParameter("@Grade", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter CourseDate
			{
				get
				{
					return new SqlParameter("@CourseDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter UserID
			{
				get
				{
					return new SqlParameter("@UserID", SqlDbType.UniqueIdentifier, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string CourseID = "CourseID";
            public const string Grade = "Grade";
            public const string CourseDate = "CourseDate";
            public const string UserID = "UserID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CourseID] = _UserCourse.PropertyNames.CourseID;
					ht[Grade] = _UserCourse.PropertyNames.Grade;
					ht[CourseDate] = _UserCourse.PropertyNames.CourseDate;
					ht[UserID] = _UserCourse.PropertyNames.UserID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string CourseID = "CourseID";
            public const string Grade = "Grade";
            public const string CourseDate = "CourseDate";
            public const string UserID = "UserID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CourseID] = _UserCourse.ColumnNames.CourseID;
					ht[Grade] = _UserCourse.ColumnNames.Grade;
					ht[CourseDate] = _UserCourse.ColumnNames.CourseDate;
					ht[UserID] = _UserCourse.ColumnNames.UserID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string CourseID = "s_CourseID";
            public const string Grade = "s_Grade";
            public const string CourseDate = "s_CourseDate";
            public const string UserID = "s_UserID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int CourseID
	    {
			get
	        {
				return base.Getint(ColumnNames.CourseID);
			}
			set
	        {
				base.Setint(ColumnNames.CourseID, value);
			}
		}

		public virtual int Grade
	    {
			get
	        {
				return base.Getint(ColumnNames.Grade);
			}
			set
	        {
				base.Setint(ColumnNames.Grade, value);
			}
		}

		public virtual DateTime CourseDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.CourseDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.CourseDate, value);
			}
		}

		public virtual Guid UserID
	    {
			get
	        {
				return base.GetGuid(ColumnNames.UserID);
			}
			set
	        {
				base.SetGuid(ColumnNames.UserID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_CourseID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CourseID) ? string.Empty : base.GetintAsString(ColumnNames.CourseID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CourseID);
				else
					this.CourseID = base.SetintAsString(ColumnNames.CourseID, value);
			}
		}

		public virtual string s_Grade
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Grade) ? string.Empty : base.GetintAsString(ColumnNames.Grade);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Grade);
				else
					this.Grade = base.SetintAsString(ColumnNames.Grade, value);
			}
		}

		public virtual string s_CourseDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CourseDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.CourseDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CourseDate);
				else
					this.CourseDate = base.SetDateTimeAsString(ColumnNames.CourseDate, value);
			}
		}

		public virtual string s_UserID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserID) ? string.Empty : base.GetGuidAsString(ColumnNames.UserID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserID);
				else
					this.UserID = base.SetGuidAsString(ColumnNames.UserID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CourseID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CourseID, Parameters.CourseID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Grade
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Grade, Parameters.Grade);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CourseDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CourseDate, Parameters.CourseDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CourseID
		    {
				get
		        {
					if(_CourseID_W == null)
	        	    {
						_CourseID_W = TearOff.CourseID;
					}
					return _CourseID_W;
				}
			}

			public WhereParameter Grade
		    {
				get
		        {
					if(_Grade_W == null)
	        	    {
						_Grade_W = TearOff.Grade;
					}
					return _Grade_W;
				}
			}

			public WhereParameter CourseDate
		    {
				get
		        {
					if(_CourseDate_W == null)
	        	    {
						_CourseDate_W = TearOff.CourseDate;
					}
					return _CourseDate_W;
				}
			}

			public WhereParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			private WhereParameter _CourseID_W = null;
			private WhereParameter _Grade_W = null;
			private WhereParameter _CourseDate_W = null;
			private WhereParameter _UserID_W = null;

			public void WhereClauseReset()
			{
				_CourseID_W = null;
				_Grade_W = null;
				_CourseDate_W = null;
				_UserID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CourseID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CourseID, Parameters.CourseID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Grade
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Grade, Parameters.Grade);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CourseDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CourseDate, Parameters.CourseDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CourseID
		    {
				get
		        {
					if(_CourseID_W == null)
	        	    {
						_CourseID_W = TearOff.CourseID;
					}
					return _CourseID_W;
				}
			}

			public AggregateParameter Grade
		    {
				get
		        {
					if(_Grade_W == null)
	        	    {
						_Grade_W = TearOff.Grade;
					}
					return _Grade_W;
				}
			}

			public AggregateParameter CourseDate
		    {
				get
		        {
					if(_CourseDate_W == null)
	        	    {
						_CourseDate_W = TearOff.CourseDate;
					}
					return _CourseDate_W;
				}
			}

			public AggregateParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			private AggregateParameter _CourseID_W = null;
			private AggregateParameter _Grade_W = null;
			private AggregateParameter _CourseDate_W = null;
			private AggregateParameter _UserID_W = null;

			public void AggregateClauseReset()
			{
				_CourseID_W = null;
				_Grade_W = null;
				_CourseDate_W = null;
				_UserID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserCourseInsert]";
	
			CreateParameters(cmd);
			    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserCourseUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_UserCourseDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.CourseID);
			p.SourceColumn = ColumnNames.CourseID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CourseDate);
			p.SourceColumn = ColumnNames.CourseDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserID);
			p.SourceColumn = ColumnNames.UserID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.CourseID);
			p.SourceColumn = ColumnNames.CourseID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Grade);
			p.SourceColumn = ColumnNames.Grade;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CourseDate);
			p.SourceColumn = ColumnNames.CourseDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserID);
			p.SourceColumn = ColumnNames.UserID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
