
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Corsat.DAL
{
	public abstract class _Video_Tags : SqlClientEntity
	{
		public _Video_Tags()
		{
			this.QuerySource = "Video_Tags";
			this.MappingName = "Video_Tags";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_Video_TagsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ID, ID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_Video_TagsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ID
			{
				get
				{
					return new SqlParameter("@ID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Video_TagsID
			{
				get
				{
					return new SqlParameter("@Video_TagsID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Tag
			{
				get
				{
					return new SqlParameter("@Tag", SqlDbType.NVarChar, 200);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ID = "ID";
            public const string Video_TagsID = "Video_TagsID";
            public const string Tag = "Tag";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _Video_Tags.PropertyNames.ID;
					ht[Video_TagsID] = _Video_Tags.PropertyNames.Video_TagsID;
					ht[Tag] = _Video_Tags.PropertyNames.Tag;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ID = "ID";
            public const string Video_TagsID = "Video_TagsID";
            public const string Tag = "Tag";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _Video_Tags.ColumnNames.ID;
					ht[Video_TagsID] = _Video_Tags.ColumnNames.Video_TagsID;
					ht[Tag] = _Video_Tags.ColumnNames.Tag;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ID = "s_ID";
            public const string Video_TagsID = "s_Video_TagsID";
            public const string Tag = "s_Tag";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ID
	    {
			get
	        {
				return base.Getint(ColumnNames.ID);
			}
			set
	        {
				base.Setint(ColumnNames.ID, value);
			}
		}

		public virtual int Video_TagsID
	    {
			get
	        {
				return base.Getint(ColumnNames.Video_TagsID);
			}
			set
	        {
				base.Setint(ColumnNames.Video_TagsID, value);
			}
		}

		public virtual string Tag
	    {
			get
	        {
				return base.Getstring(ColumnNames.Tag);
			}
			set
	        {
				base.Setstring(ColumnNames.Tag, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ID) ? string.Empty : base.GetintAsString(ColumnNames.ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ID);
				else
					this.ID = base.SetintAsString(ColumnNames.ID, value);
			}
		}

		public virtual string s_Video_TagsID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Video_TagsID) ? string.Empty : base.GetintAsString(ColumnNames.Video_TagsID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Video_TagsID);
				else
					this.Video_TagsID = base.SetintAsString(ColumnNames.Video_TagsID, value);
			}
		}

		public virtual string s_Tag
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Tag) ? string.Empty : base.GetstringAsString(ColumnNames.Tag);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Tag);
				else
					this.Tag = base.SetstringAsString(ColumnNames.Tag, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Video_TagsID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Video_TagsID, Parameters.Video_TagsID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Tag
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Tag, Parameters.Tag);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter Video_TagsID
		    {
				get
		        {
					if(_Video_TagsID_W == null)
	        	    {
						_Video_TagsID_W = TearOff.Video_TagsID;
					}
					return _Video_TagsID_W;
				}
			}

			public WhereParameter Tag
		    {
				get
		        {
					if(_Tag_W == null)
	        	    {
						_Tag_W = TearOff.Tag;
					}
					return _Tag_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _Video_TagsID_W = null;
			private WhereParameter _Tag_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_Video_TagsID_W = null;
				_Tag_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Video_TagsID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Video_TagsID, Parameters.Video_TagsID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Tag
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Tag, Parameters.Tag);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter Video_TagsID
		    {
				get
		        {
					if(_Video_TagsID_W == null)
	        	    {
						_Video_TagsID_W = TearOff.Video_TagsID;
					}
					return _Video_TagsID_W;
				}
			}

			public AggregateParameter Tag
		    {
				get
		        {
					if(_Tag_W == null)
	        	    {
						_Tag_W = TearOff.Tag;
					}
					return _Tag_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _Video_TagsID_W = null;
			private AggregateParameter _Tag_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_Video_TagsID_W = null;
				_Tag_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Video_TagsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Video_TagsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_Video_TagsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Video_TagsID);
			p.SourceColumn = ColumnNames.Video_TagsID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Tag);
			p.SourceColumn = ColumnNames.Tag;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
